---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildpack
  namespace: buildpack
---
# DON'T FORGET TO CREATE THE CONFIGMAP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-poc
  namespace: buildpack
spec:
  template:
    spec:
     volumes:
       - name: cache
         emptyDir: {}
       - name: workspace
         emptyDir: {}
       - name: dockerfile-volume
         configMap:
           name: dockerfile
     restartPolicy: Never
     containers:
       - name: bud
         image: kind-registry:5000/buildah-app
         env:
         - name: LOGGING_FORMAT
           value: "color"
         - name: LOGGING_LEVEL
           value: "debug"
         - name: ROOT_FS_DIR
           value: "/"
         - name: WORKSPACE_DIR
           value: "/workspace"
         - name: EXTRACT_LAYERS
           value: "true"
         - name:  FILES_TO_SEARCH
           value: "good.txt"
         workingDir: /workspace
         command: [ "/buildah-app" ]
         volumeMounts:
         - name: cache
           mountPath: /cache
         - name: workspace
           mountPath: /workspace
         - name: dockerfile-volume
           mountPath: /workspace/Dockerfile
           subPath: Dockerfile
         imagePullPolicy: Always
     serviceAccountName: buildpack

