[[dockerfiles]]
extension_id = "sample/cert"
path = "/layers/cert/Dockerfile"
build = true
run = false

[[dockerfiles.args.build]]
name = "some_arg"
value = "some-arg-build-value"

[[dockerfiles.args.build]]
name = "base_image"
value = "ubuntu"