{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "engine-poc.serviceAccountName" . }}
  labels:
    {{- include "engine-poc.labels" . | nindent 4 }}
{{- end }}
automountServiceAccountToken: false