processes = []

[[buildpacks]]
api = "0.7"
homepage = "https://github.com/buildpacks/samples/tree/main/extensions/curl"
id = "samples/curl"
version = "0.0.1"
extension = true

[[buildpacks]]
api = "0.7"
homepage = "https://github.com/buildpacks/samples/tree/main/extensions/rebasable"
id = "samples/rebasable"
version = "0.0.1"
extension = true

[[dockerfiles]]
extension_id = "samples/curl"
path = "/layers/samples_curl/Dockerfile"
build = true
run = true

[[dockerfiles.args]]
name = "some_arg"
value = "some-arg-build-value"

[[dockerfiles.args]]
name = "some_arg"
value = "some-arg-launch-value"

[[dockerfiles]]
extension_id = "samples/rebasable"
path = "/cnb/ext/samples_rebasable/0.0.1/Dockerfile"
build = true
run = true
