apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "buildah-poc.fullname" . }}
  labels:
    {{- include "buildah-poc.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      serviceAccountName: {{ include "buildah-poc.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOGGING_FORMAT
              value: "color"
            {{- if .Values.buildah.loggingLevel }}
            - name: LOGGING_LEVEL
              value: {{ .Values.buildah.loggingLevel }}
            {{- end }}
            {{- if .Values.buildah.rootFSDir }}
            - name: ROOT_FS_DIR
              value: {{ .Values.buildah.rootFSDir }}
            {{- end }}
            {{- if .Values.buildah.workspaceDir }}
            - name: WORKSPACE_DIR
              value: {{  .Values.buildah.workspaceDir }}
            {{- end }}
            {{- if .Values.buildah.extractLayers }}
            - name: EXTRACT_LAYERS
              value: {{ .Values.buildah.extractLayers | quote }}
            {{- end }}
            {{- if .Values.buildah.filesToSearch }}
            - name:  FILES_TO_SEARCH
              value: {{ .Values.buildah.filesToSearch }}
            {{- end }}
            {{- if .Values.buildah.dockerfilenameToBuild }}
            - name: DOCKERFILE_NAME
              value: {{ .Values.buildah.dockerfilenameToBuild }}
            {{- end }}
            {{- if .Values.buildah.metadataTomlFileName }}
            - name: METADATA_FILE_NAME
              value: {{ .Values.buildah.metadataTomlFileName }}
            {{- end }}
          workingDir: /workspace
          command: [ "/buildah-app" ]
          volumeMounts:
            - name: cache
              mountPath: /cache

