on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    env:
      KIND_CL_NAME: e2e-dummy
      ENGINE: buildah
    if: contains(github.event.head_commit.message, 'dummy')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean resident local docker
        if: ${{ env.ACT }}
        continue-on-error: true
        run: |
          for DIMG in "$KIND_CL_NAME-control-plane "; do
            docker stop $DIMG ; docker rm $DIMG ;
          done ;
          sleep 1

      - name: Create Kubernetes Kind Cluster
        uses: container-tools/kind-action@v1.7.0
        with:
          cluster_name: e2e-test
          registry: true
          config: ./${{ env.ENGINE }}/hack/kind-config.yml

      - name: Tag and push the image
        run: |
          docker pull gcr.io/google-samples/hello-app:1.0
          docker tag gcr.io/google-samples/hello-app:1.0 $KIND_REGISTRY/hello-app:1.0
          docker push $KIND_REGISTRY/hello-app:1.0

      - name: Deploy a k8s hello app
        run: |
          cat <<'EOF' | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello
            labels:
              app: hello
          spec:
            volumes:
              - name: workspace
                hostPath:
                  path: "/workspace"
            restartPolicy: Never
            initContainers:
              - name: dummy
                image: alpine:3
                command: [ "/bin/sh","-c" ]
                args:
                  - |
                    ls -la /workspace
                volumeMounts:
                  - name: workspace
                    mountPath: /workspace
            containers:
               - name: bud
                 image: kind-registry:5000/hello-app:1.0
                 volumeMounts:
                   - name: workspace
                     mountPath: /workspace
          EOF

          kubectl logs -lapp=hello -c dummy -f

          #while true; do
          #  if kubectl -n default wait --for=condition=ready pod -lapp=hello 2>/dev/null; then
          #    pod_status=0
          #    break
          #  fi
          #  sleep 3
          #done
          #
          #if [[ $pod_status -eq 1 ]]; then
          #    echo "Pod failed to start!"
          #    exit 1
          #fi
          #
          #echo "Pod succeeded to start"
          #exit 0

      - name: Delete cluster
        run: kind delete cluster


