on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    env:
      KIND_CL_NAME: e2e-dummy
      ENGINE: buildah
    if: contains(github.event.head_commit.message, 'dummy')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Kubernetes using Kind tool
        uses: container-tools/kind-action@v1.7.0
        with:
          registry: true

      - name: Tag and push the image
        working-directory: ${{ env.ENGINE }}
        run: |
          cat <<'EOF' > Dockerfile
          FROM gcr.io/google-samples/hello-app:1.0
          COPY ./wks/ /workspace
          EOF
          docker build -t my-hello-app:1.0 .

          docker tag my-hello-app:1.0 $KIND_REGISTRY/my-hello-app:1.0
          docker push $KIND_REGISTRY/my-hello-app:1.0

      - name: Deploy a k8s hello app
        run: |
          cat <<'EOF' | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello
            labels:
              app: hello
          spec:
            restartPolicy: Never
            initContainers:
              - name: dummy
                image: kind-registry:5000/my-hello-app:1.0
                command: [ "/bin/sh","-c" ]
                args:
                  - |
                    ls -la /
                    ls -la /workspace
            containers:
               - name: bud
                 image: kind-registry:5000/hello-app
          EOF

          sleep 10s
          # kubectl logs -n default -lapp=hello -c dummy --tail=-1

          while true; do
            if kubectl -n default wait --for=condition=ready pod -lapp=hello 2>/dev/null; then
              pod_status=0
              break
            fi
            sleep 3
          done

          if [[ $pod_status -eq 1 ]]; then
              echo "Pod failed to start!"
              exit 1
          fi

          echo "Pod succeeded to start"
          exit 0

      - name: Delete cluster
        run: kind delete cluster


